name: project_kuliah_mwsp_uts_kel4
description: "bijiapp"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ===== UI & ICON =====
  cupertino_icons: ^1.0.8
  line_awesome_flutter: ^3.0.1
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^2.0.1
  flutter_colorpicker: ^1.0.3

  # ===== NETWORKING & STORAGE (WAJIB UNTUK AUTH) =====
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatar/
    - assets/images/background/
    - assets/images/menus/
    - assets/images/menus/list/
    - assets/images/menus/slide/
    - assets/images/svg/
    - assets/images/svg/icons/
    - assets/images/social/
    - assets/images/cart/
    - assets/images/profile/
    - assets/images/card/
    - assets/images/store/
